name: Tagging demo
on:
  push:
    branches:
      - main
      - develop
      - features/**
    paths:
      - "src/**"
      - "./.github/workflows/demo.yaml"
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - develop
      - features/**
    paths:
      - "src/**"
      - "./.github/workflows/demo.yaml"

  workflow_dispatch:

jobs:
  tagging:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "logging"
      - name: CheckCondition
        if: |
          github.ref == 'refs/heads/main'
          || github.ref == 'refs/heads/develop'
        run: |
          echo "condition"
